### ISSUE TITLE
IOS 11.4.1 iphone 6 doesn't work

### ISSUE THREAD

**Issue by b33son** [MABelanger/react-html5-camera-photo#15]
On an iPhone 6 with IOS 11.4.1 using Chrome phone I get the following error: 
Camera error: null is not an object (evaluating 'V.mediaDevices.getUserMedia')

I confirmed that the same phone using Safari works.

**Comment by MABelanger** [comment]
Yep, i will put it into the readme : 
Since iOS11,

WebRTC is partially supported in WKWebView, 
and fully supported in the Safari App browser. 

WebRTC has three main JavaScript APIs:
* MediaStream (aka getUserMedia)
* RTCPeerConnection
* RTCDataChannel

https://stackoverflow.com/questions/45055329/does-webkit-in-ios-11-beta-support-webrtc
